wandb_version: 1

out_dir:
  desc: null
  value: out
eval_interval:
  desc: null
  value: 2000
log_interval:
  desc: null
  value: 1
eval_iters:
  desc: null
  value: 50
always_save_checkpoint:
  desc: null
  value: true
init_from:
  desc: null
  value: resume
eval_only:
  desc: null
  value: false
wandb_log:
  desc: null
  value: true
wandb_project:
  desc: null
  value: Automatic Drum Transcription
wandb_run_name:
  desc: null
  value: HTDemucs1705752480.280994
dataset:
  desc: null
  value: e-gmd-v1.0.0
gradient_accumulation_steps:
  desc: null
  value: 16
batch_size:
  desc: null
  value: 2
sample_rate:
  desc: null
  value: 44100
sample_length:
  desc: null
  value: 12
block_size:
  desc: null
  value: 529200
audio_channels:
  desc: null
  value: 1
depth:
  desc: null
  value: 4
t_layers:
  desc: null
  value: 5
t_heads:
  desc: null
  value: 8
t_dropout:
  desc: null
  value: 0.0
t_weight_decay:
  desc: null
  value: 0.0
samplerate:
  desc: null
  value: 44100
velocity_branch:
  desc: null
  value: true
learning_rate:
  desc: null
  value: 0.0003
max_iters:
  desc: null
  value: 600000
weight_decay:
  desc: null
  value: 0.05
beta1:
  desc: null
  value: 0.9
beta2:
  desc: null
  value: 0.999
grad_clip:
  desc: null
  value: 5.0
decay_lr:
  desc: null
  value: true
warmup_iters:
  desc: null
  value: 2000
lr_decay_iters:
  desc: null
  value: 600000
min_lr:
  desc: null
  value: 3.0e-05
velocity_loss_coeff:
  desc: null
  value: 0.5
device:
  desc: null
  value: cuda
dtype:
  desc: null
  value: float32
compile:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1705752482.784728
    t:
      1:
      - 1
      - 50
      - 55
      - 71
      2:
      - 1
      - 50
      - 55
      - 71
      3:
      - 13
      - 16
      - 23
      4: 3.9.18
      5: 0.16.2
      8:
      - 5
      13: linux-x86_64
